### ISSUE TITLE
Find a better method of writing all logs to file when tearing down an experiment

### ISSUE THREAD

**Issue by DWatkins** [rosmod/webgme-rosmod#151]
enables the user to set a high logging unit to reduce overhead and not worry about losing logs that have not be written to file.

**Comment by finger563** [comment]
Short term:
* modify ROSMOD-COMM so that `rosmod_actor` has a signal handler for a non-kill / terminate signal in which it calls a function on all component instances (possibly their destructors)
* modify ROSMOD-COMM so that component base class exposes a function which encapsulates logger->write()
* modify WebGME-ROSMOD so that the stop experiment sends the new signal, waits, then sends the kill signal (currently just sends kill signal).

**Comment by finger563** [comment]
Long term:
* enable communication between WebGME-ROSMOD server and ROSMOD components to allow for actor lifecycle management, reconfiguration, redeployment, etc.

**Comment by finger563** [comment]
possibly can integrate with #172 which should enable sending of controls and other data to ROSMOD components at runtime.

**Comment by finger563** [comment]
see: https://answers.ros.org/question/191787/sigint-handler-not-working/ and https://answers.ros.org/question/27655/what-is-the-correct-way-to-do-stuff-before-a-node-is-shutdown/ for proper ways of inserting signal handlers into nodes.

**Comment by finger563** [comment]
use the `-signal` option of [pkill](https://linux.die.net/man/1/pkill)
