### ISSUE TITLE
Deadlines for component instances

### ISSUE THREAD

**Issue by pranav-srinivas-kumar** [rosmod/webgme-rosmod#26]
We want to be able to set deadlines for component instances so that we don't have to recompile during experimentation.

**Comment by finger563** [comment]
Will need to figure out how this will work in the META since the component instance only has indirect references to the original component and its timers/ports and their attributes.

**Comment by finger563** [comment]
We may want to change to not have `Component Instance` be a meta-type; if we allow components in the deployment model; we can say that the user should create the component by dragging it in from the tree browser and selecting `instance`.  This would allow properties to be inherited and also overridden.

**Comment by finger563** [comment]
With respect to creating an `instance` of a `component`, we'd have to figure out how to determine the original component's name, since the user can rename the component instance we'd lose track of the name of the component library required for it.  Additionally there are some deployment specific concerns that would need to be moved from the current `Component Instance` to the `Component` (e.g. `SchedulingScheme`, `EnableLogging`, and `LogingUnit`).  Probably need to discuss this further.

**Comment by finger563** [comment]
The only missing dependency now is the resolution of https://github.com/rosmod/rosmod-actor/issues/3 before we can close this issue.
