### ISSUE TITLE
We need a Pre-Experiment script launcher

### ISSUE THREAD

**Issue by pranav-srinivas-kumar** [rosmod/webgme-rosmod#29]
Currently, in the Run_Experiment plugin, we have a hard-coded command "'export DISPLAY=:0.0'" in the start_processes function. Such commands are a property of the application and not the deployment infrastructure. So, commands like these need to be prepared in the model and therefore required as a concept in the metamodel.

**Comment by finger563** [comment]
From our discussion, this seems to be a property of the component itself (e.g. because the specific component requires the use of a display?) and therefore a multi-line string attribute akin to a bash script should be provided for pre-execution commands?  The user would not need to type things like `export LD_LIBRARY_PATH=$PWD:$LD_LIBRARY_PATH` or `export ROS_IP=<IP>`, since those are still handled by the deployment infrastructure, but we'd need a way to input commands after that which are required by the user.

**Comment by finger563** [comment]
Multi-line attributes `startup` and `teardown` might be useful.  The main issue is how to delineate commands that might be different for different systems.  Initially, not allowing system-specific info but just enabling some more customization of components / component instances might be beneficial.
