### ISSUE TITLE
Notifications window cannot handle large messages

### ISSUE THREAD

**Issue by DWatkins** [rosmod/webgme-rosmod#54]
![notifications](https://cloud.githubusercontent.com/assets/455381/14407334/2eb498b4-fe8a-11e5-97ff-527ae6487d6a.png)

**Comment by finger563** [comment]
Can you let me know what you were trying to do when seeing this message?

**Comment by DWatkins** [comment]
Running the software generator to compile code for the copy of client-server example I was making.  Sources files generated just fine, but the error is thrown when trying to compile.  The error in its entirety is shown in the following screenshot.
![message](https://cloud.githubusercontent.com/assets/455381/14407373/0a46a9d4-fe8c-11e5-9ad6-3919264ce170.png)

**Comment by finger563** [comment]
I'm going to push an update to the code which closes this specific issue (i.e. it splits the strings into multiple notifications.)  Please open a new issue with some information about the specific error you get from this compilation / copying because I believe that is another issue that needs to be taken care of.
